### PR TITLE
Fix mutex context in ScheduleAfterIfSuccess for Executor

### LINKED ISSUE #4820: Orbit crashed when trying to connect to QT application
I'm playing with Orbit and trying to profile qt5 `animatedtiles` application (standard example in qt). When I select the application in the processes list and double-click it to start the session, Orbit crashes. I think both Orbit and this app share the same qt5 base libraries, but it's should not be a problem.

```
[mutex.cc : 1388] RAW: Acquiring absl::Mutex 0x55d3a3765270 while holding  0x55d3a42aa2c0 0x55d3a3765270 0x55d3a42a3f10 0x55d3a44b43e0 0x55d3a42e1580; a cycle in the historical lock ordering graph has been observed
[mutex.cc : 1392] RAW: Cycle: 
[mutex.cc : 1406] RAW: mutex@0x55d3a3765270 stack: 
	@ 0x55d3a2486dec absl::DebugOnlyDeadlockCheck()
	@ 0x55d3a248725b absl::Mutex::ReaderLock()
	@ 0x55d3a1755435 absl::ReaderMutexLock::ReaderMutexLock()
	@ 0x55d3a19f93cd orbit_base::Executor::ScheduleAfter<>()::{lambda()#1}::operator()<>()
	@ 0x55d3a1a2d37e std::__invoke_impl<>()
	@ 0x55d3a1a2cdec std::__invoke<>()
	@ 0x55d3a1a2c718 std::invoke<>()
	@ 0x55d3a1a2bd52 orbit_base::AnyInvocable<>::Storage<>::invoke()
	@ 0x55d3a1a3d0fb orbit_base::AnyInvocable<>::operator()()
	@ 0x55d3a1a37cd3 orbit_base::Promise<>::SetResult()
	@ 0x55d3a1a30eef orbit_base::UnwrapFuture<>()::{lambda()#1}::operator()()::{lambda()#1}::operator()()
	@ 0x55d3a1a60a9a std::__invoke_impl<>()
	@ 0x55d3a1a604f1 std::__invoke<>()
	@ 0x55d3a1a60071 std::invoke<>()
	@ 0x55d3a1a5ee30 orbit_base::AnyInvocable<>::Storage<>::invoke()
	@ 0x55d3a1a3d0fb orbit_base::AnyInvocable<>::operator()()
	@ 0x55d3a1a37cd3 orbit_base::Promise<>::SetResult()
	@ 0x55d3a19ffaaa orbit_base::HandleErrorAndSetResultInPromise<>::Call<>()
	@ 0x55d3a19ecd9a orbit_base::ImmediateExecutor::ScheduleAfterIfSuccess<>()::{lambda()#1}::operator()()
	@ 0x55d3a1a2cf22 std::__invoke_impl<>()
	@ 0x55d3a1a2c894 std::__invoke<>()
	@ 0x55d3a1a2c2bc std::invoke<>()
	@ 0x55d3a1a2b836 orbit_base::AnyInvocable<>::Storage<>::invoke()
	@ 0x55d3a193ebc3 orbit_base::AnyInvocable<>::operator()()
	@ 0x55d3a193097d orbit_base::Promise<>::SetResult()
	@ 0x55d3a19f4deb orbit_base::Executor::ScheduleAfterIfSuccess<>()::{lambda()#1}::operator()()
	@ 0x55d3a1a2ce68 std::__invoke_impl<>()
	@ 0x55d3a1a2c7b0 std::__invoke<>()
	@ 0x55d3a1a2c202 std::invoke<>()
	@ 0x55d3a1a2b704 orbit_base::AnyInvocable<>::Storage<>::invoke()
	@ 0x55d3a1a41127 orbit_base::AnyInvocable<>::operator()()
	@ 0x55d3a1a3b69b orbit_base::Promise<>::SetResult()
	@ 0x55d3a1a0283d orbit_base::CallTaskAndSetResultInPromise<>::Call<>()
	@ 0x55d3a19f414a orbit_base::Executor::Schedule<>()::{lambda()#1}::operator()()
	@ 0x55d3a1a2c022 NullaryFunctorAction<>::Execute()
	@ 0x55d3a18bb2b7 OrbitApp::OrbitApp()::{lambda()#1}::operator()()
	@ 0x55d3a19067f5 std::__invoke_impl<>()
	@ 0x55d3a18fd8be std::__invoke_r<>()
	@ 0x55d3a18f7a28 std::_Function_handler<>::_M_invoke()
	@ 0x55d3a244191f std::function<>::operator()()

[mutex.cc : 1411] RAW: dying due to potential deadlock
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by alexkalmuk**
Fixes #4820.
I've created a unit test to demonstrate what's happening in case of the inner future ended with an error.  In Debug version (and before the fix) the test ended with:
```
[mutex.cc : 1411] RAW: dying due to potential deadlock
Aborted (core dumped)
```
In Release version, the test passes. But absl documentation says that "Neither read-locks nor write-locks are reentrant/recursive", so it would be safer to fix it.

I've extracted promise->SetResult out of mutex locked context for Executor. In ImmediateExecutor there are no locks, so nothing is required for that case.

### CODE REVIEW

**Comment by beckerhe** [comment]
Awesome. Thank you Alex for that fix. I will don't have time today to look at this, but tomorrow should work out.

**Comment by alexkalmuk** [comment]
> Awesome. Thank you Alex for that fix. I will don't have time today to look at this, but tomorrow should work out.

No worries. I still need some time to make clang happy. Also, I must to learn how to use clang-tidy locally to avoid ping-pong with CI.

File: src/OrbitBase/include/OrbitBase/Executor.h [hunk 1]
```diff
@@ -181,7 +181,14 @@ class Executor : public std::enable_shared_from_this<Executor> {
       // might do things that need synchronization and can't happen in a different context (like a
       // thread pool), i.e. when the continuation owns a ScopedStatus.
       if (argument.has_error()) {
+        // Here in SetResult other continuations might be called to propogate the result,
+        // and some of these continuations might result in calling of ScheduleAfter() which locks
+        // the same executor mutex. To avoid possible deadlocks, execute SetResult() here
+        // in the non-locked context.
+        executor_handle.data_->mutex_.ReaderUnlock();
         promise.SetResult(outcome::failure(argument.error()));
+        executor_handle.data_->mutex_.ReaderLock();
```
Comment (beckerhe) [inline src/OrbitBase/include/OrbitBase/Executor.h:190]: When re-acquiring the lock we also have to check again whether the executor is still alive (similar to line 176) because the executor could have gone out of scope in the mean-time.

But I think the better approach would be to narrow the scope of the lock to the actual `ScheduleImpl` calls. As far as I can see this shouldn't have any detrimental side effects.

So here it would become:

```cpp
promise.SetResult(outcome::failure(argument.error()));

absl::ReaderMutexLock lock{&executor_handle.data_->mutex_};
if (executor_handle.data_->executor_ == nullptr) return;

executor_handle.data_->executor_->ScheduleImpl(CreateAction(
  [this, function_reference]() { waiting_continuations_.erase(function_reference); }));
return;
```

and down after the `success_function_wrapper` we would need the same.

WDYT?

Comment (beckerhe) [reply src/OrbitBase/include/OrbitBase/Executor.h:190]: Yep, this was my idea. There is no way around having two locks I guess.

Comment (alexkalmuk) [reply src/OrbitBase/include/OrbitBase/Executor.h:190]: Great, I'll fix it (most likely, today in the evening).

Comment (alexkalmuk) [reply src/OrbitBase/include/OrbitBase/Executor.h]: Fixed.

**Review by beckerhe — APPROVED** [review]
Thank you Alex. Looks good to me!
