### PR TITLE
Remove top from obtaining CPU usage information

### LINKED ISSUE #1157: Problem: Unable to determine cpu utilization, wrong format from top command
OS: Ubuntu 20.04
Build: Development tip (9b6fbf49e99d65206637427d26cb489e9e590fdd)

Output from GetCpuUtilization() command (Utils.cpp)
```
damian@damian-GP72-7RD:~/projects/dependencies/development/orbit$ top -b -n 1 -w512 | sed -n '8, 1000{s/^ *//;s/ *$//;s/  */,/gp;};1000q'
32677,damian,20,0,20788,4116,3196,R,18.8,0.0,0:00.03,top
10104,damian,20,0,9057244,194136,112008,S,12.5,1.2,3:35.18,chrome
2182,root,20,0,485288,109752,66004,S,6.2,0.7,5:03.74,Xorg
2332,damian,20,0,393964,7792,5548,S,6.2,0.0,0:31.72,ibus-daemon
2448,damian,20,0,4944696,360448,82532,S,6.2,2.2,6:08.59,gnome-shell
3060,damian,20,0,915032,58128,32612,S,6.2,0.4,1:12.80,gnome-terminal-
7974,damian,20,0,670268,128780,64516,S,6.2,0.8,3:14.49,chrome
```
The columns are correct, so an attempt at parsing could be made.
```
damian@damian-GP72-7RD:~/projects/dependencies/development/orbit$ top -b -n 1 -w512
top - 08:38:00 up  1:27,  1 user,  load average: 0.97, 1.14, 1.42
Tasks: 452 total,   1 running, 451 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.0 us,  5.0 sy,  0.0 ni, 88.8 id,  0.0 wa,  0.0 hi,  1.2 si,  0.0 st
MiB Mem :  15806.1 total,    358.7 free,   5903.6 used,   9543.8 buff/cache
MiB Swap:   2048.0 total,   1957.0 free,     91.0 used.   8267.9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
```

The issue appears to be that occassionally there are more columns than expected:
```
9669,damian,20,0,4060172,19696,13096,S,11.8,0.1,2:28.33,ignore,-,main 14
618,root,20,0,0,0,0,S,0.0,0.0,0:00.00,UVM,global,queu 14
618,root,20,0,0,0,0,S,0.0,0.0,0:00.00,UVM,global,queu 14
618,root,20,0,0,0,0,S,0.0,0.0,0:00.00,UVM,global,queu 14
```

Modifying the following (OrbitService/Utils.cpp)
```
ErrorMessageOr<std::unordered_map<pid_t, double>> GetCpuUtilization(std::string_view top_data) {
  std::unordered_map<pid_t, double> process_map;
  for (const auto& line : absl::StrSplit(top_data, '\n')) {
    if (line.empty()) continue;
    std::vector<std::string> tokens = absl::StrSplit(line, ',');
    if (tokens.size() < 12) {
      return ErrorMessage(
          "Unable to determine cpu utilization, wrong format from top "
          "command.");
    }

    pid_t pid = strtol(tokens[0].c_str(), nullptr, 10);
    double cpu = strtod(tokens[8].c_str(), nullptr);
    process_map[pid] = cpu;
  }

  return process_map;
}
```

allows this method to work.

### PR DESCRIPTION
**Pull request by beckerhe**
Up to now we use top for getting CPU usage information per process.
This requires a fixed output format of top and is slow since top has to
run a certain time interval for averaging CPU usage.

We can do the same internally by reading /proc/stat and
/proc/[pid]/stat. This commit adds this logic to
orbit_service::ProcessList.

The routines reading from `/proc` live in orbit_service::utils and are
unit-tested.

The CPU usage is averaged between two consecutive calls of
ProcessList::Refresh. This means the averaging time period is not always
constant and depends on when Refresh is called. But I believe it's good
enough for our use case.

Test: Manual test, compared process list cpu output to top running in
shell
Bug: http://b/165823980
Fixes #1157

### CODE REVIEW

File: OrbitService/Process.cpp [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+    process.set_full_path(std::move(file_path_result.value()));
+
+    const auto& elf_file = ElfUtils::ElfFile::Create(file_path_result.value().string());
+    if (elf_file) {
+      process.set_is_64_bit(elf_file.value()->Is64Bit());
+    } else {
+      LOG("Warning: Unable to parse the executable \"%s\" as elf file. (pid: %d)",
+          file_path_result.value(), pid);
+    }
+  }
```
Comment (beckerhe) [inline OrbitService/Process.cpp:94]: This part was previously living in ProcessList.cpp and was moved here.

File: OrbitService/Process.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  std::string name = std::move(name_file_result.value());
+  // Remove new line character.
+  absl::StripTrailingAsciiWhitespace(&name);
+  if (name.empty()) {
+    return ErrorMessage{"Could not determine the process name"};
+  }
+
+  Process process{};
+  process.set_pid(pid);
+  process.set_name(name);
```
Comment (beckerhe) [inline OrbitService/Process.cpp:60]: This part was previously living in ProcessList.cpp and was moved here.

File: OrbitService/Utils.cpp [hunk 3]
```diff
@@ -175,29 +158,117 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
+    return {};
+  }
+
+  std::string first_line{};
+  std::getline(stream, first_line);
+
+  std::vector<std::string_view> fields = absl::StrSplit(first_line, ' ', absl::SkipWhitespace{});
+
+  constexpr size_t utime_index = 13;
+  constexpr size_t stime_index = 14;
```
Comment (dpallotti) [inline OrbitService/Utils.cpp:215]: `kUtimeIndex`, `kStimeIndex`?

File: OrbitService/Utils.cpp [hunk 4]
```diff
@@ -175,29 +158,117 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
+  template <typename T>
+  std::vector<T> operator()(std::vector<T> vec, const std::optional<T>& val) const {
+    if (val.has_value()) {
+      vec.emplace_back(std::move(val.value()));
+    }
+
+    return std::move(vec);
+  }
+};
+}  // namespace
```
Comment (dpallotti) [inline OrbitService/Utils.cpp:189]: Is it not possible to use a lambda instead?

File: OrbitService/ProcessList.h [hunk 5]
```diff
@@ -9,20 +9,61 @@
...
+    [[nodiscard]] bool operator()(const pid_t lhs, const Process& rhs) const {
+      return lhs == rhs.pid();
+    }
+
+    [[nodiscard]] bool operator()(const Process& lhs, const pid_t rhs) const {
+      return lhs.pid() == rhs;
+    }
+  };
+
+  absl::flat_hash_set<Process, ProcessHash, ProcessEq> processes_;
```
Comment (dpallotti) [inline OrbitService/ProcessList.h:66]: Wouldn't a map from int32_t to orbit_grpc_protos::ProcessInfo be more intuitive? I have to say that I find it unnecessary complicated to have to define hash and equality that work for both Process and pid_t when the access is (or can be) only by pid.

File: OrbitService/Process.cpp [hunk 6]
```diff
@@ -0,0 +1,99 @@
+// Copyright (c) 2020 The Orbit Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+#include "Process.h"
```
Comment (dimitry-) [inline OrbitService/Process.cpp:5]: would be nice to have commit moving Process separate from this commit - this way it is more visible what was changed.

File: OrbitService/Process.h [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+
+#ifndef ORBIT_SERVICE_PROCESS_H_
+#define ORBIT_SERVICE_PROCESS_H_
+
+#include "Utils.h"
+#include "process.pb.h"
+
+namespace orbit_service {
+
+struct Process : orbit_grpc_protos::ProcessInfo {
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.h:13]: `struct` and `class` have identical meaning, but `struct` has more sensible defaults. (Public members by default which is nice when you want to put private members at the bottom / public inheritance). But I can change if you prefer a `class`. I don't have a strong opinion here.

[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.h:13]: It's public inheritance since it's a struct.

File: OrbitService/ProcessList.cpp [hunk 8]
```diff
@@ -41,66 +33,44 @@ ErrorMessageOr<void> ProcessList::Refresh() {
...
-    auto iter = processes_map_.find(pid);
-    if (iter != processes_map_.end()) {
-      ProcessInfo& process(*(iter->second));
-      process.set_cpu_usage(cpu_usage_map[process.pid()]);
-      updated_processes.push_back(process);
-      continue;
-    }
+    const auto iter = processes_.find(pid);
+    if (iter != processes_.end()) {
+      auto process = processes_.extract(iter);
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/ProcessList.cpp:38]: extract returns the internal `node_type` which can the be inserted in another map container. This is/can be more efficient.

File: OrbitService/ProcessListTest.cpp [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+#include "OrbitBase/Logging.h"
+#include "ProcessList.h"
+#include "gtest/gtest.h"
+
+namespace orbit_service {
+
+TEST(ProcessList, ProcessList) {
+  ProcessList process_list;
+  const auto result1 = process_list.Refresh();
+  ASSERT_TRUE(result1) << result1.error().message();
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/ProcessListTest.cpp:17]: I don't mind to write it differently. In this particular case I copied the code from somewhere else because of the stream-operator which I hadn't used yet in gtest.

File: OrbitService/ProcessList.h (hunk 5 above)
Comment (beckerhe) [reply OrbitService/ProcessList.h:66]: Since `ProcessInfo` already contained the PID, it would mean that the PID is stored in the key and in the value-struct and must be kept in sync. For me personally this feels bug-prone, semantically wrong and less intuitive than a set.

Can you explain where you see the complexity? I admit, defining ProcessHash and ProcessEq is verbose, but is it difficult? Maybe I'm misjudging that...

File: OrbitService/Process.cpp (hunk 6 above)
Comment (beckerhe) [reply OrbitService/Process.cpp:5]: I will tackle that when Davide's comments are resolved.

File: OrbitService/Process.cpp [hunk 10]
```diff
@@ -0,0 +1,99 @@
...
+
+  previous_process_cpu_time_ = process_cpu_time;
+  previous_total_cpu_time_ = total_cpu_time;
+}
+
+ErrorMessageOr<Process> Process::FromPid(pid_t pid) {
+  const auto path = std::filesystem::path{"/proc"} / std::to_string(pid);
+
+  if (!std::filesystem::is_directory(path)) {
+    return ErrorMessage{absl::StrFormat("PID %d does not exist!", pid)};
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.cpp]: Ahhhh. Good point. Fixed.

File: OrbitService/Process.cpp [hunk 11]
```diff
@@ -0,0 +1,99 @@
...
+  if (!name_file_result) {
+    return ErrorMessage{absl::StrFormat("Failed to read %s: %s", name_file_path.string(),
+                                        name_file_result.error().message())};
+  }
+
+  std::string name = std::move(name_file_result.value());
+  // Remove new line character.
+  absl::StripTrailingAsciiWhitespace(&name);
+  if (name.empty()) {
+    return ErrorMessage{"Could not determine the process name"};
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.cpp]: Good idea. Done.

File: OrbitService/Process.h [hunk 12]
```diff
@@ -0,0 +1,29 @@
...
+  using orbit_grpc_protos::ProcessInfo::ProcessInfo;
+
+  void UpdateCpuUsage(utils::Jiffies process_cpu_time, utils::Jiffies total_cpu_time);
+
+  // Creates a `Process` by reading details from the `/proc` filesystem.
+  // This might failed due to a non existing pid or due to permission problems.
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.h]: Thanks!

File: OrbitService/ProcessList.cpp [hunk 13]
```diff
@@ -41,66 +33,44 @@ ErrorMessageOr<void> ProcessList::Refresh() {
...
-      } else {
-        LOG("Warning: Unable to parse the executable \"%s\" as elf file. (pid: %d)",
-            file_path_result.value(), pid);
-      }
+    if (process) {
+      updated_processes.emplace(std::move(process.value()));
+    } else {
+      // We don't fail in this case. This could be a permission problem which is restricted to a
+      // small amount of processes.
+      ERROR("Could not create process list entry for pid %d. Details: %s", pid,
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/ProcessList.cpp]: Yes. Thanks. Fixed.

File: OrbitService/Utils.cpp (hunk 3 above)
Comment (beckerhe) [reply OrbitService/Utils.cpp]: Done.

File: OrbitService/Utils.cpp (hunk 4 above)
Comment (beckerhe) [reply OrbitService/Utils.cpp]: Yeah, good point. This was used in two different functions before, but I could simplifiy the code and forgot to remove that helper function again. Thanks!

File: OrbitService/Process.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.h:13]: I just saw the google style guide prefers `class` in this case. I will change it!

[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Process.h]: Fixed. Thanks!

File: OrbitService/CMakeLists.txt [hunk 14]
```diff
@@ -67,7 +69,8 @@ strip_symbols(OrbitService)
 add_executable(OrbitServiceTests)
 target_compile_options(OrbitServiceTests PRIVATE ${STRICT_COMPILE_FLAGS})
 
-target_sources(OrbitServiceTests PRIVATE UtilsTest.cpp Utils.cpp)
+target_sources(OrbitServiceTests PRIVATE UtilsTest.cpp ProcessTest.cpp
+                                         ProcessListTest.cpp)
```
Comment (antonrohr) [inline OrbitService/CMakeLists.txt:73]: nit
```suggestion
target_sources(OrbitServiceTests PRIVATE UtilsTest.cpp
                                         ProcessTest.cpp
                                         ProcessListTest.cpp)
```

File: OrbitService/ProcessTest.cpp [hunk 15]
```diff
@@ -0,0 +1,25 @@
+// Copyright (c) 2020 The Orbit Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+#include <unistd.h>
+
+#include "OrbitBase/Logging.h"
```
Comment (antonrohr) [inline OrbitService/ProcessTest.cpp:7]: nit
```suggestion

```

File: OrbitService/ProcessList.cpp [hunk 16]
```diff
@@ -41,66 +33,43 @@ ErrorMessageOr<void> ProcessList::Refresh() {
...
+      const auto cpu_time = utils::GetCumulativeCpuTimeFromProcess(process.value().pid());
+      if (cpu_time && total_cpu_time) {
+        process.value().UpdateCpuUsage(cpu_time.value(), total_cpu_time.value());
+      } else {
+        // We don't fail in this case. This could be a permission problem which might occur when not
+        // running as root.
+        ERROR("Could not update the CPU usage of process %d", process.value().pid());
+      }
+
+      updated_processes.insert(std::move(process));
```
Comment (antonrohr) [inline OrbitService/ProcessList.cpp:50]: Should this maybe only be done when we succeed in updating the cpu usage? Just an idea. Feel free to dismiss

File: OrbitService/ProcessListTest.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (antonrohr) [reply OrbitService/ProcessListTest.cpp:17]: I like how it is done currently. (Also, the stream operator is independent from the bool conversion. If i understood it right, the stream operator is only for producing better error messages)

File: OrbitService/ProcessList.h (hunk 5 above)
Comment (beckerhe) [reply OrbitService/ProcessList.h:66]: It would be great to get some other opinions of that. Obviously I like my code :sweat_smile: , but I'm also happy to comply with the majority. :see_no_evil:

File: OrbitService/ProcessListTest.cpp [hunk 17]
```diff
@@ -0,0 +1,37 @@
...
+
+  const auto process1 = process_list.GetProcessByPid(getpid());
+  EXPECT_TRUE(process1);
+
+  const auto total_cpu_cycles = utils::GetCumulativeTotalCpuTime().value();
+
+  // We wait until the stats have been updated
+  while (utils::GetCumulativeTotalCpuTime().value().value == total_cpu_cycles.value) {
+    // If this loop never ends it will be caught by the automatic timeout feature
+    usleep(10'000);
```
Comment (antonrohr) [inline OrbitService/ProcessListTest.cpp:27]: If you use the test timeout as a thing, consider adding the following to the cmake file. (I think the default timeout is 30 minutes and that is excessive)
`set_tests_properties(OrbitService PROPERTIES TIMEOUT 10)`

File: OrbitService/ProcessList.h (hunk 5 above)
Comment (dimitry-) [reply OrbitService/ProcessList.h:66]: I also think map looks better here.

File: OrbitService/ProcessListTest.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/ProcessListTest.cpp:17]: Yes, I only mentioned the streaming operator to explain that I copied that code from somewhere else where the streaming operator was used.

File: OrbitService/ProcessList.h (hunk 5 above)
Comment (beckerhe) [reply OrbitService/ProcessList.h]: Alright. I changed it to a `absl::flat_hash_map<pid_t, Process>`.

File: OrbitService/UtilsTest.cpp [hunk 18]
```diff
@@ -96,44 +97,57 @@ TEST(Utils, ParseMaps) {
 
 }  // namespace orbit_service::utils
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/UtilsTest.cpp]: Done. Thanks.

File: OrbitService/Utils.cpp [hunk 19]
```diff
@@ -175,29 +158,112 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
+std::vector<pid_t> GetAllPids() {
+  const auto emplace_back_if_has_value = [](auto vec, const auto& val) {
+    if (val.has_value()) {
+      vec.emplace_back(std::move(val.value()));
+    }
+
+    return std::move(vec);
+  };
+
+  std::filesystem::directory_iterator proc{"/proc"};
```
[the remark this answers is not in the document]
Comment (beckerhe) [reply OrbitService/Utils.cpp]: Yes. Done. Thanks.

File: OrbitService/CMakeLists.txt (hunk 14 above)
Comment (beckerhe) [reply OrbitService/CMakeLists.txt]: Done.

File: OrbitService/ProcessTest.cpp (hunk 15 above)
Comment (beckerhe) [reply OrbitService/ProcessTest.cpp]: Nice catch! Thanks. Done.

File: OrbitService/ProcessList.cpp (hunk 16 above)
Comment (beckerhe) [reply OrbitService/ProcessList.cpp:50]: Good question. I thought about these kind of things and decided that I don't want to change behaviour in this PR. Not reading CPU usage is something which usually happens only when the service is not running as root which is currently out of scope. We should probably think about how to handle that in the future, things like differentiating between processes that can be profiled and these that can't.

File: OrbitService/ProcessListTest.cpp (hunk 17 above)
Comment (beckerhe) [reply OrbitService/ProcessListTest.cpp:27]: Good point. Done. Thanks.

**Comment by beckerhe** [comment]
I'm going to split the commits now and the re-request a review from you.

File: OrbitService/ProcessList.cpp (hunk 16 above)
Comment (antonrohr) [reply OrbitService/ProcessList.cpp:50]: Sounds good

File: OrbitService/Process.cpp (hunk 6 above)
Comment (beckerhe) [reply OrbitService/Process.cpp:5]: This is now in a separate commit. I'm going to make some more tests before I re-request review.

File: OrbitService/ProcessList.cpp [hunk 20]
```diff
@@ -43,55 +41,20 @@ ErrorMessageOr<void> ProcessList::Refresh() {
 
     auto iter = processes_map_.find(pid);
     if (iter != processes_map_.end()) {
-      ProcessInfo& process(*(iter->second));
+      Process& process(*(iter->second));
```
Comment (dimitry-) [inline OrbitService/ProcessList.cpp]: it looks a bit weird - this initialized reference not an object correct? maybe use = here?

File: OrbitService/Process.cpp [hunk 21]
```diff
@@ -19,7 +19,22 @@
...
-ErrorMessageOr<Process> Process::FromPidAndCpuUsage(pid_t pid, double cpu_usage) {
+void Process::UpdateCpuUsage(utils::Jiffies process_cpu_time, utils::Jiffies total_cpu_time) {
+  const auto diff_process_cpu_time =
+      static_cast<double>(process_cpu_time.value - previous_process_cpu_time_.value);
+  const auto diff_total_cpu_time =
+      static_cast<double>(total_cpu_time.value - previous_total_cpu_time_.value);
+
+  const auto cpu_usage = std::clamp(diff_process_cpu_time / diff_total_cpu_time, 0.0, 1.0);
+
+  // TODO(hebecker): Rename cpu_usage to cpu_usage_percent. Not being normalized was surprising
```
Comment (dimitry-) [inline OrbitService/Process.cpp:30]: interesting - maybe we should do the opposite and use rate here - normalize on the client-side.

File: OrbitService/Process.cpp [hunk 22]
```diff
@@ -19,7 +19,22 @@
...
 namespace orbit_service {
 
-ErrorMessageOr<Process> Process::FromPidAndCpuUsage(pid_t pid, double cpu_usage) {
+void Process::UpdateCpuUsage(utils::Jiffies process_cpu_time, utils::Jiffies total_cpu_time) {
+  const auto diff_process_cpu_time =
+      static_cast<double>(process_cpu_time.value - previous_process_cpu_time_.value);
+  const auto diff_total_cpu_time =
+      static_cast<double>(total_cpu_time.value - previous_total_cpu_time_.value);
+
+  const auto cpu_usage = std::clamp(diff_process_cpu_time / diff_total_cpu_time, 0.0, 1.0);
```
Comment (dimitry-) [inline OrbitService/Process.cpp:28]: can this be less than 0?

File: OrbitService/ProcessList.cpp [hunk 23]
```diff
@@ -18,14 +17,7 @@
...
 ErrorMessageOr<void> ProcessList::Refresh() {
-  auto cpu_result = utils::GetCpuUtilization();
-  if (!cpu_result) {
-    return outcome::failure(absl::StrFormat("Unable to retrieve cpu usage of processes: %s",
-                                            cpu_result.error().message()));
-  }
-  std::unordered_map<int32_t, double> cpu_usage_map = std::move(cpu_result.value());
-
-  std::vector<Process> updated_processes;
+  decltype(processes_) updated_processes{};
```
Comment (dimitry-) [inline OrbitService/ProcessList.cpp:20]: use explicit type here decltype is not very readable.

File: OrbitService/Process.cpp (hunk 22 above)
Comment (dimitry-) [inline OrbitService/Process.cpp:28]: Could it be < 0 or more than 1?

File: OrbitService/Utils.cpp [hunk 24]
```diff
@@ -175,29 +158,112 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
+
+std::optional<Jiffies> GetCumulativeCpuTimeFromProcess(pid_t pid) {
+  const auto stat = std::filesystem::path{"/proc"} / std::to_string(pid) / "stat";
+
+  if (!std::filesystem::exists(stat)) {
+    return {};
+  }
+
+  std::ifstream stream{stat.string()};
+  if (!stream.good()) {
```
Comment (dimitry-) [inline OrbitService/Utils.cpp:200]: log something here (not sure if it will result in spam in logs though)?

File: OrbitService/Utils.cpp [hunk 25]
```diff
@@ -175,29 +158,112 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
+    return std::move(vec);
+  };
+
+  fs::directory_iterator proc{"/proc"};
+  return std::transform_reduce(begin(proc), end(proc), std::vector<pid_t>{},
+                               emplace_back_if_has_value, ProcEntryToPid);
+}
+
+std::optional<Jiffies> GetCumulativeCpuTimeFromProcess(pid_t pid) {
+  const auto stat = std::filesystem::path{"/proc"} / std::to_string(pid) / "stat";
```
Comment (dimitry-) [inline OrbitService/Utils.cpp:193]: add comment with format/example of /stat so this is clear which part this function is extracting.

File: OrbitService/Utils.cpp [hunk 26]
```diff
@@ -175,29 +158,112 @@ ErrorMessageOr<std::vector<orbit_grpc_protos::TracepointInfo>> ReadTracepoints()
...
-  std::unordered_map<pid_t, double> process_map;
-  for (const auto& line : absl::StrSplit(top_data, '\n')) {
-    if (line.empty()) continue;
-    std::vector<std::string> tokens = absl::StrSplit(line, ',');
-    if (tokens.size() != 12) {
-      return ErrorMessage(
-          "Unable to determine cpu utilization, wrong format from top "
-          "command.");
+std::optional<Jiffies> GetCumulativeTotalCpuTime() {
+  std::ifstream stat_stream{"/proc/stat"};
```
Comment (dimitry-) [inline OrbitService/Utils.cpp:230]: same here.

**Review by dimitry- — APPROVED** [review]
otherwise lgtm

**Review by antonrohr — APPROVED** [review]
Thanks for including the changes

File: OrbitService/ProcessList.cpp (hunk 20 above)
Comment (beckerhe) [reply OrbitService/ProcessList.cpp]: I agree. done.

File: OrbitService/Process.cpp (hunk 21 above)
Comment (beckerhe) [reply OrbitService/Process.cpp]: Good point. I adjusted the comment.

File: OrbitService/Process.cpp (hunk 22 above)
Comment (beckerhe) [reply OrbitService/Process.cpp:28]: No, it can't because Jiffies is unsigned. But it can be bigger than 1.0 when the counter wraps.

But if Jiffies were signed we would get a negative values in the wrapping case. So I had two choices: Either add a static_assert which ensure that Jiffies is unsigned or add the clamp. I felt that the clamp is less surprising. It's also part of all the examples I've on the internet. (top has clamp, htop as well, the stuff on StackOverflow also has it.)

Do you think it's misleading?

File: OrbitService/ProcessList.cpp (hunk 23 above)
Comment (beckerhe) [reply OrbitService/ProcessList.cpp]: Done.

File: OrbitService/Process.cpp (hunk 22 above)
Comment (beckerhe) [reply OrbitService/Process.cpp:28]: See other comment.

File: OrbitService/Utils.cpp (hunk 24 above)
Comment (beckerhe) [reply OrbitService/Utils.cpp:209]: Done.

File: OrbitService/Utils.cpp (hunk 25 above)
Comment (beckerhe) [reply OrbitService/Utils.cpp:193]: Done.

File: OrbitService/Utils.cpp (hunk 26 above)
Comment (beckerhe) [reply OrbitService/Utils.cpp:240]: Done.

**Comment by beckerhe** [comment]
I made some more tests. Output looks good, even after all the changes. Capturing also seems to work fine.

**Comment by beckerhe** [comment]
I will wait for Davide before merging.

File: OrbitService/Process.cpp (hunk 22 above)
Comment (dimitry-) [reply OrbitService/Process.cpp:28]: no but I think it deserves a short comment as of when it can be > 1.0

Comment (beckerhe) [reply OrbitService/Process.cpp:31]: Yes, that makes sense. Done. And thank you!

File: OrbitService/ProcessList.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (dpallotti) [reply OrbitService/ProcessList.cpp:36]: Ah interesting, thanks!

**Review by dpallotti — APPROVED** [review]

File: OrbitService/Process.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (dpallotti) [reply OrbitService/Process.h]: Yeah, this was part of not being used to `struct` instead of `class` in such a case. Thanks for changing to `class`.
